language: python
python:
- '2.7'
- '3.5'
sudo: false
branches:
  only:
  - master
install:
- pip install -r requirements/tox.txt
- pip install tox-travis
script:
- tox
after_success:
- pip install coveralls
- coveralls
deploy:
  provider: pypi
  user: edx
  password:
    secure: lxud//HWpP4gZq9PaYIA3DOds6tYKXpWG6aFNzRYf5fnQgTEkZKgFt22n7bepEae+1JM6n53aUtXFQpS8wPi4VQaHU35y8OGHKXNbZnLc4MX8vKsnNaGghX0CVkLw6BlQ2SYLpA3p4pWiqoXLucmon64GntVLqRumG3MqbaRFuCLGjrZEH+GX4zN9QdzAmvvCI0BiKYr+wRmztiAwoqfY4GB8C4/3J2W4p6UfumFJ9jRtkkDDesXx/w6b99teppJrSoAFs2dYg0i9qhwpvmwmPnF+e3AtxenqaDT7pO0x3hNk9GMMFqz76XYuOORSmS5mI5WyDonFgbSCGdtCPg5b1zdAAQklMugnZ1e+l1awN1BGpOpLfMTIHV9HewfLvW1lMiECQK1g91HFOcMII7+qA7xOx1MPbW1OvNadwsifn/94BcMPngb6Bc6OJZwTOR7SOIoNjSJLkyZ+RGUScMYpyb0WJBy0p9N4eGPBi7pWAoTtHT8+5itw6wMjB/qw60kRjiXa5Xkm4UUExRgUsV0qsXaWQrxK5TmEGGMDCpZd2Qw7I3Lw4Lj+DJ/FwSoJbZ0C0PEvYeXrU8dhEj22h1vzKltR2d8uiZYK6eSmVAM7KboLTztkGqtdYTQIzzKRjYu/EvoC+qnHl3qG8W8geTK0+MwFZRzHjK8Cnv+lY4buGA=
  distributions: sdist bdist_wheel
  on:
    tags: true
